# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/codecov/all/codecov.rbi
#
# codecov-0.1.17

class SimpleCov::Formatter::Codecov
  def build_params(ci); end
  def detect_ci; end
  def display_header; end
  def file_to_codecov(file); end
  def format(result); end
  def net_blockers(switch); end
  def result_to_codecov(result); end
  def result_to_codecov_coverage(result); end
  def result_to_codecov_messages(result); end
  def shortened_filename(file); end
  def upload_to_codecov(req, https); end
end
