# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simplecov-cobertura/all/simplecov-cobertura.rbi
#
# simplecov-cobertura-2.1.0

module SimpleCov
end
module SimpleCov::Formatter
end
class SimpleCov::Formatter::CoberturaFormatter
  def coverage_output(result); end
  def extract_rate(percent); end
  def format(result); end
  def initialize(result_file_name: nil); end
  def project_root; end
  def resolve_filename(filename); end
  def result_to_xml(result); end
  def set_branch_attributes(line, file_line, branched_lines, branched_lines_covered); end
  def set_class_attributes(class_, file); end
  def set_coverage_attributes(coverage, result); end
  def set_line_attributes(line, file_line); end
  def set_package_attributes(package, name, result); end
  def set_xml_head(lines = nil); end
end
