# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module RedisRecord::Logger::ClassMethods::Rails; end
module RedisRecord::RedisConnection::ClassMethods::Rails; end
module RedisRecord::RedisConnection::Rails; end
module RedisRecord::TTL::ClassMethods::ActiveSupport::Duration; end
module T::Private::Methods::SingletonMethodHooks; end
