name: ci

on:
  push:
    branches: # Trigger only on the main branch to avoid duplicate runs on PR branches
      - master
  pull_request: # Trigger All PRs

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.1, ruby-head]
        use_cluster: [true, false]
        include:
          - ruby: 3.1 # TODO(mattxwang): remove this ASAP!
            experimental: true # a hack to allow tests to fail for ruby-head, https://github.com/actions/toolkit/issues/399
          - ruby: ruby-head
            experimental: true # a hack to allow tests to fail for ruby-head, https://github.com/actions/toolkit/issues/399

    env:
      REDCORD_SPEC_USE_CLUSTER: ${{ matrix.use_cluster }}

    services:
      redis:
        image: redis:5-alpine
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli GET 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Sorbet Typecheck (allowed to fail)
      run: bundle exec srb tc | true
    - name: "Run Tests (allowed failure: ${{ matrix.experimental == true }})"
      run: bundle exec rspec || ${{ matrix.experimental == true }} # the eq forces a boolean instead of an empty string
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/coverage.xml
